### ISSUE TITLE
Implement polling strategy (maybe?)

### ISSUE THREAD

**Issue by ognjenkatic** [codaxy/conductor-sharp#2]
Quoting existing TODO from code:

`// TODO: Implement polling strategy so that if there
    // are no requests incoming we poll less, and when queues are full
    // we poll more often`

This basically means that when there is a high load we poll more often and when there is no load we extend the polling interval to be kind to conductor (as there are many microservices individually polling it).

I am not 100% sure this would make much of a difference as we cannot allot a too long polling interval (5s+) because new tasks would end up waiting a lot. We did notice in production scenarios that conductor is affected by heavy polling.

**Comment by boma96** [comment]
@ognjenkatic This is implemented?
